/***************************************************************************
 # Copyright (c) 2015-23, NVIDIA CORPORATION. All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions
 # are met:
 #  * Redistributions of source code must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
 #  * Redistributions in binary form must reproduce the above copyright
 #    notice, this list of conditions and the following disclaimer in the
 #    documentation and/or other materials provided with the distribution.
 #  * Neither the name of NVIDIA CORPORATION nor the names of its
 #    contributors may be used to endorse or promote products derived
 #    from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS "AS IS" AND ANY
 # EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 # IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 # PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 # CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 # EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 # PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 # PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 # OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **************************************************************************/
__exported import Scene.Shading;
__exported import Utils.Timing.GpuTimer;
__exported import Utils.Math.Ray;
import Utils.Math.MathHelpers;
import Utils.Sampling.SampleGenerator;

RWTexture2D<PackedHitInfo> gVBuffer;
RWTexture2D<float> gDepth;
RWTexture2D<float2> gMotionVector;
RWTexture2D<float4> gViewW;

RWTexture2D<float4> gThp;      //
RWTexture2D<float4> gEmissive; //
RWTexture2D<float4> gNormale;  //
RWTexture2D<float4> gAlbedo;   //
RWTexture2D<float4> gPosition; //

RWTexture2D<float4> gViewW_first;
RWTexture2D<float4> gThp_first;      //
RWTexture2D<float4> gNormale_first;  //
RWTexture2D<float4> gAlbedo_first;   //
RWTexture2D<float4> gPosition_first; //

RWTexture2D<float2> gUV;
RWTexture2D<uint> gMeshID;

RWTexture2D<uint> gTime;
RWTexture2D<float> gMask;

#define is_valid(name) (is_valid_##name != 0)

#if !defined(COMPUTE_DEPTH_OF_FIELD) || !defined(USE_ALPHA_TEST) || !defined(RAY_FLAGS)
#error "Not all defines are set!"
#endif

struct VBufferSC
{
    // From the UI settings
    static const bool kComputeDepthOfField = COMPUTE_DEPTH_OF_FIELD;
    static const bool kUseAlphaTest = USE_ALPHA_TEST;
    static const uint kRayFlags = RAY_FLAGS;
    uint2 frameDim;
    uint frameCount;

    // Generate a Ray from the pixel coordinate and the camera
    Ray generateRay(uint2 pixel, inout SampleGenerator sg)
    {
        if (kComputeDepthOfField)
        {
            return gScene.camera.computeRayThinlens(pixel, frameDim, sampleNext2D(sg));
        }
        else
        {
            return gScene.camera.computeRayPinhole(pixel, frameDim);
        }
    }

    void writeHit(
        uint2 pixel,
        float3 rayOrigin,
        float3 rayDir,
        float3 throughPut,
        float3 emissive,
        const HitInfo hit,
        const float linZ,
        float3 color,
        float3 position
    )
    // void writeHit(uint2 pixel, float3 rayOrigin, float3 rayDir, float3 thp, float3 emissive, const HitInfo hit)
    {
        gVBuffer[pixel] = hit.pack();
        gThp[pixel] = float4(throughPut, 1.f);
        gEmissive[pixel] = float4(emissive, 1.f);
        gViewW[pixel] = float4(-rayDir, 1.f);
        gAlbedo[pixel] = float4(color, 1.f);
        gPosition[pixel] = float4(position, 1.f);

        VertexData v;
        float depth = 1.f;
        float3 prevPosW = float3(0.f);
        float2 motionVector = float2(0.f);

        if (hit.getType() == HitType::Triangle)
        {
            const TriangleHit triangleHit = hit.getTriangleHit();
            v = gScene.getVertexData(triangleHit);
            prevPosW = gScene.getPrevPosW(triangleHit);
            gMeshID[pixel] = triangleHit.instanceID.index+1;

            // normal
            uint materialID = gScene.getMaterialID(triangleHit.instanceID);
            let lod = ExplicitLodTextureSampler(0.f);
            ShadingData sd = gScene.materials.prepareShadingData(v, materialID, -rayDir);
            float3 geometry_normal = sd.faceN;
            adjustShadingNormal(sd, sd.frame);
            float3 shading_normal = sd.frame.N;
            float normal_adjust_factor = dot(geometry_normal, shading_normal);
            // gNormale[pixel] = float4(geometry_normal, 1.f);

            gNormale[pixel] = float4(shading_normal, 1.f);
            // gNormale[pixel] = float4(normal_adjust_factor, normal_adjust_factor, normal_adjust_factor, 1.f);
        }
        else if (hit.getType() == HitType::DisplacedTriangle)
        {
            const DisplacedTriangleHit displacedTriangleHit = hit.getDisplacedTriangleHit();
            v = gScene.getVertexData(displacedTriangleHit, -rayDir);
            prevPosW = gScene.getPrevPosW(displacedTriangleHit);
        }
        else if (hit.getType() == HitType::Curve)
        {
            const CurveHit curveHit = hit.getCurveHit();
            v = gScene.getVertexDataFromCurve(curveHit);
            prevPosW = gScene.getPrevPosWFromCurve(curveHit);
        }
        else if (hit.getType() == HitType::SDFGrid)
        {
            const SDFGridHit sdfGridHit = hit.getSDFGridHit();
            v = gScene.getVertexDataFromSDFGrid(sdfGridHit, rayOrigin, rayDir);

            prevPosW = gScene.getPrevPosWFromSDFGrid(sdfGridHit, v.posW);
        }

        if (hit.getType() == HitType::Triangle || hit.getType() == HitType::DisplacedTriangle || hit.getType() == HitType::Curve ||
            hit.getType() == HitType::SDFGrid)
        {
            // Compute depth similar to raster (NDC).
            float4 curPosH = mul(gScene.camera.data.viewProjMatNoJitter, float4(v.posW, 1.f));
            depth = curPosH.z / curPosH.w;

            // Compute motion vector.
            float2 pixelPos = pixel + float2(0.5f, 0.5f);
            float4 prevPosH = mul(gScene.camera.data.prevViewProjMatNoJitter, float4(prevPosW, 1.f));
            // Remove camera jitter from motion vector
            motionVector = calcMotionVector(pixelPos, prevPosH, frameDim) + float2(gScene.camera.data.jitterX, -gScene.camera.data.jitterY);
        }

        if (is_valid(gDepth))
            gDepth[pixel] = depth;
        if (is_valid(gMotionVector))
            gMotionVector[pixel] = motionVector;
        if (is_valid(gMask))
            gMask[pixel] = 1.0f;

        if (is_valid(gDepth))
            gDepth[pixel] = linZ;
    }

    void writeFirstHit(
        uint2 pixel,
        float3 rayOrigin,
        float3 rayDir,
        float3 throughPut,
        float3 emissive,
        const HitInfo hit,
        const float linZ,
        float3 color,
        float3 position
    ){
        gThp_first[pixel] = float4(throughPut, 1.f);
        gViewW_first[pixel] = float4(-rayDir, 1.f);
        gAlbedo_first[pixel] = float4(color, 1.f);
        gPosition_first[pixel] = float4(position, 1.f);

        VertexData v;
        float depth = 1.f;
        float3 prevPosW = float3(0.f);
        float2 motionVector = float2(0.f);

        if (hit.getType() == HitType::Triangle)
        {
            const TriangleHit triangleHit = hit.getTriangleHit();
            v = gScene.getVertexData(triangleHit);
            prevPosW = gScene.getPrevPosW(triangleHit);

            // normal
            uint materialID = gScene.getMaterialID(triangleHit.instanceID);
            let lod = ExplicitLodTextureSampler(0.f);
            ShadingData sd = gScene.materials.prepareShadingData(v, materialID, -rayDir);
            float3 geometry_normal = sd.faceN;
            adjustShadingNormal(sd, sd.frame);
            float3 shading_normal = sd.frame.N;
            float normal_adjust_factor = dot(geometry_normal, shading_normal);

            gNormale_first[pixel] = float4(shading_normal, 1.f);
        }
    }

    void writeShit(uint2 pixel, uint3 color) { gVBuffer[pixel] = uint4(color, 255); }

    void writeMiss(uint2 pixel)
    {
        gVBuffer[pixel] = {};
        gViewW[pixel] = {};
        // gUV[pixel] = (-1.f, -1.f);
        // gMeshID[pixel] = 0;

        if (is_valid(gDepth))
            gDepth[pixel] = 0.0f;
        if (is_valid(gMotionVector))
            gMotionVector[pixel] = {};
        if (is_valid(gMask))
            gMask[pixel] = 0.0f;
    }

    void writeAux(uint2 pixel, const Ray ray)
    {
        // Write view direction.
        if (is_valid(gViewW))
            gViewW[pixel] = float4(-ray.dir, 0.f);
    }

    void beginTime(inout GpuTimer timer)
    {
        if (is_valid(gTime))
            timer.start();
    }

    void endTime(uint2 pixel, inout GpuTimer timer)
    {
        if (is_valid(gTime))
            gTime[pixel] = timer.getElapsed();
    }
};

uint getMaterialInstanceHints(const HitInfo hit, const bool isPrimary)
{
    uint hints = 0;
    if (hit.getType() == HitType::Triangle || hit.getType() == HitType::DisplacedTriangle)
    {
        if (isPrimary)
            hints |= (uint)MaterialInstanceHints::AdjustShadingNormal;
        // #if GBUFFER_ADJUST_SHADING_NORMALS
        //         if (kAdjustShadingNormals || isPrimary)
        //             hints |= (uint)MaterialInstanceHints::AdjustShadingNormal;
        // #else
        //         if (kAdjustShadingNormals && !isPrimary)
        //             hints |= (uint)MaterialInstanceHints::AdjustShadingNormal;
        // #endif
    }
    hints |= (uint)MaterialInstanceHints::AdjustShadingNormal;

    return hints;
}
